title: GPCET Python
tagline: A brand new course on Learning Lab
description: GPCET Python Course
template:
  repo: gpcet-python-template
  name: gpcet-python
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
